### PR TITLE
ISD-Crew announcement

### PR DESCRIPTION
**Pull request by isd-crew**
We would like to participate at the Webtek16 by streaming an adtional livestream. We would like to add a link to our ISD Wetek frontpage (will be updated soon). 

https://isd-webtek.github.io/

Feel free to ask us more questions.

### CODE REVIEW

**Comment by isd-crew** [comment]
Sorry, I'm not really sure what the CI crash means.

**Comment by fabriziosalmi** [comment]
Welcome onboard :)))))


Il giorno gio 19 mar 2020 alle ore 12:34 isd-crew <notifications@github.com>
ha scritto:

**Comment by fabriziosalmi** [comment]
> Sorry, I'm not really sure what the CI crash means.

no prob at all for CI issues ;)

**Comment by isd-crew** [comment]
Thanks alot. See you on the web.

**Pull request merged**
